baseURL = 'https://example.org/'
locale = 'en-US'
title = 'My New Hugo Project'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Films'
    pageRef = '/films'
    weight = 20

  [[menus.main]]
    name = 'Genres'
    pageRef = '/genres'
    weight = 30

  [[menus.main]]
    name = 'Cast'
    pageRef = '/cast'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
